spring.application.name=medibook_springboot
# ===============================
# DATABASE (Turso / libSQL)
# ===============================
spring.datasource.url=${DATABASE_URL:jdbc:libsql://medibook-ehui-junior-christ.aws-ap-northeast-1.turso.io?authToken=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJleHAiOjE4MTIzNjA1NzIsImlhdCI6MTc4MDgyNDU3MiwiaWQiOiIwMTllYTE2Ny1iNjAxLTdkMzgtYjVkZi03MWQ5ODYzZGMwM2IiLCJyaWQiOiI2YWNlNGFjOC0xZTYwLTRkZjYtYTAyYi02NWU3ZjRiN2ZlZjQifQ.kEMfABFkW8fUW2Fa5VmA4wvh3vUXr7WzpJ8w8NGkHOnEbTc9KSMX7BwkvpF9LyJFRmX5m4Mm6HEGBsMlcL6NBA}
spring.datasource.driver-class-name=tech.turso.jdbc.libsql.TursoDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.community.dialect.SQLiteDialect}

# ===============================
# STATIC RESOURCES (Frontend)
# ===============================
spring.web.resources.static-locations=file:../frontend/,classpath:/static/

# ===============================
# SERVER
# ===============================
server.port=8080